name: elbazar_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: 6.1.0
  json_annotation: ^4.9.0
  riverpod: ^2.5.0
  carousel_slider: ^4.2.1
  transparent_image: ^2.0.1
  riverpod_generator: ^2.3.11
  logger: ^2.3.0
  provider: ^6.1.2
  infinite_scroll_pagination: ^4.0.0
  flutter_secure_storage: ^4.2.1
  file_picker: ^7.0.2
  fluttertoast: ^8.2.5
  form_builder_validators: ^9.1.0
  image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
